FROM ubuntu:latest
MAINTAINER Mitch Ferrer <mitch@lifeafternormal.net>

# Update Package List
RUN apt-get update

# Update all currently installed packages
RUN apt-get upgrade

# Install useful utilites
RUN apt-get -y install curl
